### PR TITLE
The 9.x release line is no longer actively maintained

### PR DESCRIPTION
**Pull request by Incognito**
Package.json should also get updated eventually.

### CODE REVIEW

**Comment by kbiedrzycki** [comment]
Looks good, however, I think we should lock version on 10.x, WDYT?

**Comment by kbiedrzycki** [comment]
Maybe also worth to update `engine` section in `package.json`?

**Comment by Incognito** [comment]
Yes absolutely, this package is obsolete without it.

**Comment by artfwo** [comment]
@Incognito @kbiedrzycki thanks!

**Pull request merged**
